language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: akOdRuqPno5Xiudsms5++n3g+uljrpsrtLVlNGSo8IXUtaILGzYvIw8egJL1RUyuHpQkpxNQQcTafUgaVWWKscsQFeJhUd7PzSQdn/W8+6E4DxfmiMbzLZOK7eFDnnEaVAIgrJR0P46dMnYpNUZQDoMW597+HieyabfUMX/IDwmVilFpDmia7tM+N1htR9KTd90P8nxfnhLWNKHILM6sR6p3hdsb0yX1HStXEEvMrqtpjXwYk+K5W31Wywx7qW8NPHQgmQQAaAPyrOZz3e/Ex5sCJ7xtJx2ekGIKG74aHmB1Q1OVNjuYaAdEK2XqpKEaKhAxf7+4LTDthYJFZtL7xOlPvpAPjHDOzLKhD9c+TtEo1YxvJT9WGaFw/ZEHaIMGmCQ2m5qmhpyLdrCcqkl5j5i/AE7ybYgPMXzqmhRNc6Vdw2DMfGCIJ8OT3DRTavGWuXEOY42Et5x4MOCbiloilE174MTiULldK5CyQQCxR8EqfSDql8AH8b85rjVLyJ8iQYWdQ1zsVp7MZicy0ZIsAIH97JFLxrVa0HGZ1uKitDuaNBERn6W1K9MONZMi8CpyeD3HIbplZ7Kkpy5pwSzRm8abLOdzti/2SF/8Clksetx0gWc8ahY1ebOh163HH9m+nzQBY2/lhzGBOrQhUesNypEO65pXnQp6Cxsfgq7EOl8=
  app: continuous-se
